apiVersion: v1
kind: Pod
metadata:
  name: pod-with-pvc
spec:
  containers:
    - name: app
      image: busybox
      command: ["sleep", "3600"]
      volumeMounts:
        - name: persistent-storage
          mountPath: /app/data
  volumes:
    - name: persistent-storage
      persistentVolumeClaim:
        claimName: demo-pvc     # Reference the PVC (not the PV directly!)
