apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dynamic-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
  # On Docker Desktop, "hostpath" is the default StorageClass
  # It will automatically create a PV for us!
  storageClassName: hostpath
