apiVersion: v1
kind: Pod
metadata:
  name: node-selector-pod
  labels:
    demo: node-selector
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    ports:
    - containerPort: 80
  nodeSelector:
    disktype: ssd
